name: ciarc_console
description: "Console for CIARC"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0-188.0.dev

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  zoom_widget: ^2.0.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: any
  protobuf: ^3.1.0
  dartssh2: ^2.11.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  injectable_generator: ^2.6.2


flutter:
  uses-material-design: true
  assets:
    - assets/map.jpg